[package]
name = "gridflow-core"
version = "0.2.0"
edition.workspace = true
license.workspace = true

[dependencies]
indexmap = "2.14.0"
logos = "0.16.1"
serde = { version = "1.0.229", features = ["derive"] }
smol_str = { version = "0.3.6", features = ["serde"] }

[dev-dependencies]
proptest = "1.11.0"
